# -*- coding: utf-8 -*-
"""Case1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Br2mSeRuBY2EYbdYtx6-x8vIZeTqZfKp

# SATRIA DATA - BIG DATA CHALLENGE (BDC)
## Case 1
##


Kelompok:Tim Anomali SCP-03

Nama Kelompok:
*   Muhamad Nizar Rahman-707012400056
*   Kerin Anggraeni-707012400066
*   Haikal Dwi Anggara-707012400113

# A. Koneksi ke GDrive
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

"""# B. Load library dan dataset"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re
import string

from sklearn.ensemble import GradientBoostingClassifier

#load data
df = pd.read_excel('/content/drive/MyDrive/TIM Anomali SCP-03/Case 1/case_1_labeled_data.xlsx')
# displaying top 10 results
df

df.info()

df['label'].value_counts().sort_index()

#import matplotlib.pyplot as plt
#import seaborn as sns

plt.figure(figsize=(10, 6))

order_label = df['label'].value_counts().index

ax = sns.countplot(
    x='label',
    data=df,
    order=order_label,
    hue='label',
    palette='viridis',
    legend=False
)

plt.title('Distribusi Kategori Label dalam Dataset')
plt.xlabel('Kategori Label')
plt.ylabel('Jumlah Sampel')
plt.xticks(rotation=45, ha='right')

for p in ax.patches:
    ax.annotate(
        int(p.get_height()),
        (p.get_x() + p.get_width() / 2, p.get_height()),
        ha='center',
        va='bottom'
    )

plt.tight_layout()
plt.show()

"""# C. Pre-processing"""

# Some functions for preprocessing text
# import re
# import string

def cleaningText(text):
    text = re.sub(r'@[A-Za-z0-9]+', '', text) # remove mentions
    text = re.sub(r'#[A-Za-z0-9]+', '', text) # remove hashtag
    text = re.sub(r'RT[\s]', '', text) # remove RT
    text = re.sub(r"http\S+", '', text) # remove link
    text = re.sub(r'[0-9]+', '', text) # remove numbers

    text = text.replace('\n', ' ') # replace new line into space
    text = text.translate(str.maketrans('', '', string.punctuation)) # remove all punctuations
    text = text.strip(' ') # remove characters space from both left and right text
    return text

def cleanEmoji(text):
    emoji = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           u"\U0001f926-\U0001f937"
                           u"\U00010000-\U0010ffff"
                           u"\u2640-\u2642"
                           u"\u2600-\u2B55"
                           u"\u200d"
                           u"\u23cf"
                           u"\u23e9"
                           u"\u231a"
                           u"\ufe0f"  # dingbats
                           u"\u3030"
                           "]+", flags=re.UNICODE)
    text = emoji.sub(r'', text)
    return text

def casefoldingText(text): # Converting all the characters in a text into lower case
    text = text.lower()
    return text

#def tokenizingText(text): # Tokenizing or splitting a string, text into a list of tokens
    #text = word_tokenize(text)
    #text = tokenizer.tokenize(text)
    #return text

#def filteringText(text): # Remove stopwors in a text
    #listStopwords = set(stopwords.words('indonesian'))
    #filtered = []
    #for txt in text:
        #if txt not in listStopwords:
            #filtered.append(txt)
    #text = filtered
    #text = filtered
    #return text

#def stemmingText(text): # Reducing a word to its word stem that affixes to suffixes and prefixes or to the roots of words
    #factory = StemmerFactory()
    #stemmer = factory.create_stemmer()
    #text = [stemmer.stem(word) for word in text]
    #text = [stemmer.stem(word) for word in text]
    #return text

#def toSentence(list_words): # Convert list of words into sentence
    #sentence = ' '.join(word for word in list_words)
    #return sentence

"""## C1. Cleaning Text & Case Folding"""

# Preprocessing data kombinasi kolom content
df['text_clean'] = df['full_text'].apply(cleaningText)
df['text_clean'] = df['text_clean'].apply(casefoldingText)
df['text_clean'] = df['text_clean'].apply(cleanEmoji)
#df.drop(['content'], axis = 1, inplace = True)

df

"""## C2. Normalisasi kata menggunakan IndoNLP

"""

!pip install indoNLP

# import re
from indoNLP.preprocessing import replace_slang, replace_word_elongation

def normalize_text_keep_mbg(text):
    text = str(text)

    # Lindungi kata mbg supaya tidak diubah oleh indoNLP
    text = re.sub(r'\bmbg\b', 'tokenmbgaman', text, flags=re.IGNORECASE)

    # Normalisasi umum
    text = replace_word_elongation(text)
    text = replace_slang(text)

    # Kembalikan token khusus menjadi mbg
    text = re.sub(r'\btokenmbgaman\b', 'mbg', text)

    # Rapikan spasi
    text = re.sub(r'\s+', ' ', text).strip()

    return text

df['text_normalized'] = df['text_clean'].apply(normalize_text_keep_mbg)

df[['full_text','text_clean', 'text_normalized', 'label']].head()

df

df[['text_clean', 'text_normalized']].sample(10)

"""## C3. Tokenisasi & Vektorisasi menggunakan Indobert"""

!pip install transformers -q

#import pandas as pd
from transformers import AutoTokenizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

df['text_input'] = df['text_normalized'].fillna('').astype(str)

label_encoder = LabelEncoder()

df['label_id'] = label_encoder.fit_transform(df['label'])

df[['label', 'label_id']].drop_duplicates().sort_values('label_id')

from sklearn.model_selection import train_test_split

label_df = df['label_id']
fitur_df = df['text_input']

# 70% train, 30% sementara
X_train, X_temp, y_train, y_temp = train_test_split(
    fitur_df,
    label_df,
    test_size=0.3,
    random_state=42,
    stratify=label_df
)

# Dari 30% sementara, dibagi menjadi 15% validation dan 15% test
X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.5,
    random_state=42,
    stratify=y_temp
)

# coba kita lihat berapa jumlah data latih dan data ujinya
print("Banyak data latih (fitur) setelah dilakukan Train-Test Split: ", len(X_train))
print("Banyak data latih (label) setelah dilakukan Train-Test Split: ", len(y_train))
print("Banyak data uji sementara (fitur) setelah dilakukan Train-Test Split: ", len(X_temp))
print("Banyak data uji sementara (label) setelah dilakukan Train-Test Split: ", len(y_temp))

print("Banyak data validasi (fitur) setelah dilakukan Train-Test Split: ", len(X_val))
print("Banyak data validasi (label) setelah dilakukan Train-Test Split: ", len(y_val))
print("Banyak data validasi (fitur) setelah dilakukan Train-Test Split: ", len(X_test))
print("Banyak data validasi (label) setelah dilakukan Train-Test Split: ", len(y_test))

print("Jumlah data train:", len(X_train))
print("Jumlah data test:", len(X_test))

print("Distribusi train:")
print(y_train.value_counts().sort_index())

print("\nDistribusi test:")
print(y_test.value_counts().sort_index())

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("indobenchmark/indobert-base-p1")

train_encodings = tokenizer(
    X_train.tolist(),
    truncation=True,
    padding=True,
    max_length=128
)

val_encodings = tokenizer(
    X_val.tolist(),
    truncation=True,
    padding=True,
    max_length=128
)

test_encodings = tokenizer(
    X_test.tolist(),
    truncation=True,
    padding=True,
    max_length=128
)

idx = 0

print("Teks asli:")
print(X_train.iloc[idx])

print("\nInput IDs:")
print(train_encodings['input_ids'][idx])

print("\nAttention Mask:")
print(train_encodings['attention_mask'][idx])

tokens = tokenizer.convert_ids_to_tokens(train_encodings['input_ids'][idx])

print("\nTokens:")
print(tokens)

idx = 0

print("Teks asli:")
print(X_train.iloc[idx])

print("\nTokens:")
print(tokenizer.convert_ids_to_tokens(train_encodings['input_ids'][idx]))

print("\nInput IDs:")
print(train_encodings['input_ids'][idx])

print("\nAttention Mask:")
print(train_encodings['attention_mask'][idx])

import pandas as pd

tokenized_train_df = pd.DataFrame({
    'text': X_train.reset_index(drop=True),
    'label_id': y_train.reset_index(drop=True),
    'input_ids': train_encodings['input_ids'],
    'attention_mask': train_encodings['attention_mask']
})

# Tambahkan bentuk token
tokenized_train_df['tokens'] = tokenized_train_df['input_ids'].apply(
    lambda x: tokenizer.convert_ids_to_tokens(x)
)

tokenized_train_df.head()

import pandas as pd

pd.set_option('display.max_colwidth', 100)

def make_encoding_dataframe(df, X_split, y_split, encodings, split_name):
    # Ambil data asli berdasarkan index X_split
    temp_df = df.loc[X_split.index, [
        'full_text',
        'text_clean',
        'text_normalized',
        'text_input',
        'label',
        'label_id'
    ]].reset_index()

    temp_df = temp_df.rename(columns={'index': 'original_index'})

    # Tambahkan hasil encoding IndoBERT
    temp_df['split'] = split_name
    temp_df['input_ids'] = encodings['input_ids']
    temp_df['attention_mask'] = encodings['attention_mask']

    # Kalau ada token_type_ids, tambahkan juga
    if 'token_type_ids' in encodings:
        temp_df['token_type_ids'] = encodings['token_type_ids']

    # Ubah input_ids menjadi token/subword
    temp_df['tokens'] = temp_df['input_ids'].apply(
        lambda x: tokenizer.convert_ids_to_tokens(x)
    )

    return temp_df

train_encoding_df = make_encoding_dataframe(
    df, X_train, y_train, train_encodings, 'train'
)

val_encoding_df = make_encoding_dataframe(
    df, X_val, y_val, val_encodings, 'validation'
)

test_encoding_df = make_encoding_dataframe(
    df, X_test, y_test, test_encodings, 'test'
)

train_encoding_df.head()

train_encoding_df[[
    'original_index',
    'full_text',
    'text_clean',
    'text_normalized',
    'label',
    'label_id',
    'tokens',
    'input_ids',
    'attention_mask'
]].head()

all_encoding_df = pd.concat(
    [train_encoding_df, val_encoding_df, test_encoding_df],
    ignore_index=True
)

all_encoding_df.head()

idx = 0

token_detail_df = pd.DataFrame({
    'token': train_encoding_df.loc[idx, 'tokens'],
    'input_id': train_encoding_df.loc[idx, 'input_ids'],
    'attention_mask': train_encoding_df.loc[idx, 'attention_mask']
})

token_detail_df = token_detail_df[token_detail_df['attention_mask'] == 1].reset_index(drop=True)

token_detail_df

# Simpan dataframe ke file Excel
all_encoding_df.to_excel('/content/drive/MyDrive/TIM Anomali SCP-03/Case 1/hasil_encoding_indobert.xlsx', index=False)

"""# D. Model Transformed Based

## D.1 Install & Import
"""

!pip install transformers -q

import torch
import pandas as pd
from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
from sklearn.preprocessing import LabelEncoder

"""## D.2 Encode label"""

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df['label_id'] = label_encoder.fit_transform(df['label'])

"""## D.3 Train test split"""

from sklearn.model_selection import train_test_split

X_train, X_temp, y_train, y_temp = train_test_split(
    df['full_text'].astype(str),
    df['label_id'],
    test_size=0.2,
    random_state=42,
    stratify=df['label_id']
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.5,
    random_state=42,
    stratify=y_temp
)

"""## D.4 Load tokenizer IndoBERT"""

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("indobenchmark/indobert-base-p1")

"""## D.5 Tokenisasi"""

train_encodings = tokenizer(list(X_train), truncation=True, padding=True, max_length=128)
val_encodings = tokenizer(list(X_val), truncation=True, padding=True, max_length=128)
test_encodings = tokenizer(list(X_test), truncation=True, padding=True, max_length=128)

"""## D.6 Dataset Class"""

import torch

class Dataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

"""## D.7 Buat Dataset"""

train_dataset = Dataset(train_encodings, y_train.tolist())
val_dataset = Dataset(val_encodings, y_val.tolist())
test_dataset = Dataset(test_encodings, y_test.tolist())

"""## D.8 Load IndoBERT Model"""

from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "indobenchmark/indobert-base-p1",
    num_labels=len(label_encoder.classes_)
)

"""## D.9 Training Argument"""

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    logging_steps=10
)

"""## D.10 Trainer"""

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset
)

"""## D.11 Train Model"""

trainer.train()

"""## D.12 Evaluasi"""

trainer.evaluate()

"""## D.13 Prediksi"""

pred = trainer.predict(test_dataset)
y_pred = pred.predictions.argmax(axis=1)

"""## D.14 Hitung Balanced Accuracy"""

from sklearn.metrics import balanced_accuracy_score
balanced_acc = balanced_accuracy_score(y_test, y_pred)
print("Balanced Accuracy:", balanced_acc)

"""## D.15 Classification report"""

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

"""#E. Gradient Boosting

##E.1 Label Encoding
"""

# FEATURE DAN LABEL

X = df['full_text']

y = df['label']

# LABEL ENCODING

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

y = label_encoder.fit_transform(y)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,
    test_size = 0.2,
    random_state = 42

)

"""##E.2 TF - IDF"""

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(

    max_features = 5000

)

X_train = tfidf.fit_transform(X_train)

X_test = tfidf.transform(X_test)

X_train = X_train.toarray()

X_test = X_test.toarray()

"""##E.3 Training Gradient Boosting"""

from sklearn.ensemble import GradientBoostingClassifier

gb_model = GradientBoostingClassifier()

gb_model.fit(X_train, y_train)

"""Prediction"""

y_pred = gb_model.predict(X_test)

"""##E.4 Balanced Scrore"""

from sklearn.metrics import balanced_accuracy_score

balanced_acc = balanced_accuracy_score(

    y_test,
    y_pred

)

print("Balanced Accuracy Score :", balanced_acc)

"""##E.5 Clasification Report"""

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy :", accuracy)

print(classification_report(y_test, y_pred))

"""##E.6 Confusion Matrix"""

from sklearn.metrics import confusion_matrix

import matplotlib.pyplot as plt

import seaborn as sns

# hitung confusion matrix

cm = confusion_matrix(y_test, y_pred)

# plot

plt.figure(figsize=(6, 4))

sns.heatmap(

    cm,
    annot=True,
    fmt='d',
    cmap='Blues'

)

plt.xlabel('Prediksi')

plt.ylabel('Aktual')

plt.title('Confusion Matrix Gradient Boosting')

plt.show()

"""#F. Optimasi: Hyperparameter Tuning dengan Gridserch CV

## F1. Tahap 1: Pencarian parameter yang optimal
"""

from sklearn.model_selection import GridSearchCV

param_grid = {

    'n_estimators': [50],
    'learning_rate': [0.1],
    'max_depth': [3],
    'min_samples_split': [2, 4],
    'min_samples_leaf': [1, 2]

}

# Buat Model Gradient BoostinG
gb_model = GradientBoostingClassifier(
    random_state = 42

)

"""## F2. Tahap 2: Proses Hyperparameter Optimization (HPO)"""

grid_search = GridSearchCV(
    estimator = gb_model,
    param_grid = param_grid,
    cv = 3,
    scoring = 'accuracy',
    n_jobs = -1,
    verbose = 2
)

"""## F3. Tahap 3: Training HPO"""

grid_search.fit(X_train, y_train)

# Ambil Parameter Terbaik
print("Best Parameters : ", grid_search.best_params_)

print("Best Score : ", grid_search.best_score_)

best_gb_model = grid_search.best_estimator_

y_pred_hpo = best_gb_model.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy_hpo = accuracy_score(

    y_test,
    y_pred_hpo

)

print("Accuracy Setelah HPO :", accuracy_hpo)

"""## F4. Tahap 4: Balanced Accuracy Setelah HPO"""

from sklearn.metrics import balanced_accuracy_score

balanced_acc_hpo = balanced_accuracy_score(

    y_test,
    y_pred_hpo

)

print("Balanced Accuracy Setelah HPO :", balanced_acc_hpo)

"""## F5. Tahap 5: Classification Report Setelah HPO"""

from sklearn.metrics import classification_report

print(classification_report(

    y_test,
    y_pred_hpo

))

"""## F6. Tahap 6: Confusion Matrix Setelah HPO"""

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

cm = confusion_matrix(
    y_test,
    y_pred_hpo
)

plt.figure(figsize=(6,4))
sns.heatmap(
    cm,
    annot = True,
    fmt = 'd',
    cmap = 'Blues'

)

plt.xlabel('Prediksi')
plt.ylabel('Aktual')
plt.title('Confusion Matrix Gradient Boosting HPO')
plt.show()

"""#DATASET 2"""

#load data
df = pd.read_excel('/content/drive/MyDrive/TIM Anomali SCP-03/Case 1/case_1_text_to_predict.xlsx')
# displaying top 10 results
df

df.info()

"""Pre Processing"""

# Some functions for preprocessing text
# import re
# import string

def cleaningText(text):
    text = re.sub(r'@[A-Za-z0-9]+', '', text) # remove mentions
    text = re.sub(r'#[A-Za-z0-9]+', '', text) # remove hashtag
    text = re.sub(r'RT[\s]', '', text) # remove RT
    text = re.sub(r"http\S+", '', text) # remove link
    text = re.sub(r'[0-9]+', '', text) # remove numbers

    text = text.replace('\n', ' ') # replace new line into space
    text = text.translate(str.maketrans('', '', string.punctuation)) # remove all punctuations
    text = text.strip(' ') # remove characters space from both left and right text
    return text

def cleanEmoji(text):
    emoji = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           u"\U0001f926-\U0001f937"
                           u"\U00010000-\U0010ffff"
                           u"\u2640-\u2642"
                           u"\u2600-\u2B55"
                           u"\u200d"
                           u"\u23cf"
                           u"\u23e9"
                           u"\u231a"
                           u"\ufe0f"  # dingbats
                           u"\u3030"
                           "]+", flags=re.UNICODE)
    text = emoji.sub(r'', text)
    return text

def casefoldingText(text): # Converting all the characters in a text into lower case
    text = text.lower()
    return text

#def tokenizingText(text): # Tokenizing or splitting a string, text into a list of tokens
    #text = word_tokenize(text)
    #text = tokenizer.tokenize(text)
    #return text

#def filteringText(text): # Remove stopwors in a text
    #listStopwords = set(stopwords.words('indonesian'))
    #filtered = []
    #for txt in text:
        #if txt not in listStopwords:
            #filtered.append(txt)
    #text = filtered
    #text = filtered
    #return text

#def stemmingText(text): # Reducing a word to its word stem that affixes to suffixes and prefixes or to the roots of words
    #factory = StemmerFactory()
    #stemmer = factory.create_stemmer()
    #text = [stemmer.stem(word) for word in text]
    #text = [stemmer.stem(word) for word in text]
    #return text

#def toSentence(list_words): # Convert list of words into sentence
    #sentence = ' '.join(word for word in list_words)
    #return sentence

"""Cleaning"""

# Preprocessing data kombinasi kolom content
df['text_clean'] = df['full_text'].apply(cleaningText)
df['text_clean'] = df['text_clean'].apply(casefoldingText)
df['text_clean'] = df['text_clean'].apply(cleanEmoji)
#df.drop(['content'], axis = 1, inplace = True)

df

"""##Normalisasi"""

!pip install indoNLP

# import re
from indoNLP.preprocessing import replace_slang, replace_word_elongation

def normalize_text_keep_mbg(text):
    text = str(text)

    # Lindungi kata mbg supaya tidak diubah oleh indoNLP
    text = re.sub(r'\bmbg\b', 'tokenmbgaman', text, flags=re.IGNORECASE)

    # Normalisasi umum
    text = replace_word_elongation(text)
    text = replace_slang(text)

    # Kembalikan token khusus menjadi mbg
    text = re.sub(r'\btokenmbgaman\b', 'mbg', text)

    # Rapikan spasi
    text = re.sub(r'\s+', ' ', text).strip()

    return text

df2['text_normalized'] = df2['text_clean'].apply(normalize_text_keep_mbg)

df2[['full_text','text_clean', 'text_normalized']].head()

df

df[['text_clean', 'text_normalized']].sample(10)

"""##Tokenisasi"""

!pip install transformers -q

#import pandas as pd
from transformers import AutoTokenizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

df['text_input'] = df['full_text'].fillna('').astype(str)

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("indobenchmark/indobert-base-p1")

train_encodings = tokenizer(
    X_train.tolist(),
    truncation=True,
    padding=True,
    max_length=128
)

val_encodings = tokenizer(
    X_val.tolist(),
    truncation=True,
    padding=True,
    max_length=128
)

test_encodings = tokenizer(
    X_test.tolist(),
    truncation=True,
    padding=True,
    max_length=128
)

idx = 0

print("Teks asli:")
print(X_train.iloc[idx])

print("\nInput IDs:")
print(train_encodings['input_ids'][idx])

print("\nAttention Mask:")
print(train_encodings['attention_mask'][idx])

tokens = tokenizer.convert_ids_to_tokens(train_encodings['input_ids'][idx])

print("\nTokens:")
print(tokens)

idx = 0

print("Teks asli:")
print(X_train.iloc[idx])

print("\nTokens:")
print(tokenizer.convert_ids_to_tokens(train_encodings['input_ids'][idx]))

print("\nInput IDs:")
print(train_encodings['input_ids'][idx])

print("\nAttention Mask:")
print(train_encodings['attention_mask'][idx])

import pandas as pd

tokenized_train_df = pd.DataFrame({
    'text': X_train.reset_index(drop=True),
    'label_id': y_train.reset_index(drop=True),
    'input_ids': train_encodings['input_ids'],
    'attention_mask': train_encodings['attention_mask']
})

# Tambahkan bentuk token
tokenized_train_df['tokens'] = tokenized_train_df['input_ids'].apply(
    lambda x: tokenizer.convert_ids_to_tokens(x)
)

tokenized_train_df.head()

import pandas as pd

pd.set_option('display.max_colwidth', 100)

def make_encoding_dataframe(df, X_split, y_split, encodings, split_name):
    # Ambil data asli berdasarkan index X_split
    temp_df = df.loc[X_split.index, [
        'full_text',
        'text_clean',
        'text_normalized',
        'text_input',
        'label',
        'label_id'
    ]].reset_index()

    temp_df = temp_df.rename(columns={'index': 'original_index'})

    # Tambahkan hasil encoding IndoBERT
    temp_df['split'] = split_name
    temp_df['input_ids'] = encodings['input_ids']
    temp_df['attention_mask'] = encodings['attention_mask']

    # Kalau ada token_type_ids, tambahkan juga
    if 'token_type_ids' in encodings:
        temp_df['token_type_ids'] = encodings['token_type_ids']

    # Ubah input_ids menjadi token/subword
    temp_df['tokens'] = temp_df['input_ids'].apply(
        lambda x: tokenizer.convert_ids_to_tokens(x)
    )

    return temp_df

def make_encoding_dataframe(X_split, y_split, encodings, split_name):
    import pandas as pd

    temp_df = pd.DataFrame({
        'text': X_split.reset_index(drop=True),
        'label_id': y_split.reset_index(drop=True),
        'input_ids': encodings['input_ids'],
        'attention_mask': encodings['attention_mask']
    })

    temp_df['split'] = split_name

    return temp_df

train_encoding_df.head()

train_encoding_df[[
    'original_index',
    'full_text',
    'text_clean',
    'text_normalized',
    'label',
    'label_id',
    'tokens',
    'input_ids',
    'attention_mask'
]].head()

all_encoding_df = pd.concat(
    [train_encoding_df, val_encoding_df, test_encoding_df],
    ignore_index=True
)

all_encoding_df.head()

idx = 0

token_detail_df = pd.DataFrame({
    'token': train_encoding_df.loc[idx, 'tokens'],
    'input_id': train_encoding_df.loc[idx, 'input_ids'],
    'attention_mask': train_encoding_df.loc[idx, 'attention_mask']
})

token_detail_df = token_detail_df[token_detail_df['attention_mask'] == 1].reset_index(drop=True)

token_detail_df

# Simpan dataframe ke file Excel
all_encoding_df.to_excel('/content/drive/MyDrive/TIM Anomali SCP-03/Case 1/hasil_encoding_indo.xlsx', index=False)

#load data
df3 = pd.read_excel('/content/drive/MyDrive/TIM Anomali SCP-03/Case 1/hasil_encoding_indo.xlsx')
# displaying top 10 results
df3

enc2 = tokenizer(list(df3['text_clean']),
                  truncation=True,
                  padding=True,
                  max_length=128)

import torch

class Dataset(torch.utils.data.Dataset):
    def _init_(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def _getitem_(self, idx):
        item = {k: torch.tensor(v[idx]) for k, v in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def _len_(self):
        return len(self.labels)

from datasets import Dataset

dataset2 = Dataset.from_dict({
    'input_ids': enc2['input_ids'],
    'attention_mask': enc2['attention_mask']
})

from datasets import Dataset

# ubah dataframe ke dataset
dataset3 = Dataset.from_pandas(df3)

enc3 = tokenizer(
    list(df3['full_text']),
    truncation=True,
    padding=True,
    max_length=128
)

from datasets import Dataset

dataset3 = Dataset.from_dict({
    'input_ids': enc3['input_ids'],
    'attention_mask': enc3['attention_mask']
})

pred2 = trainer.predict(dataset3)

logits = pred2.predictions
y_pred2 = logits.argmax(axis=1)

df3['label_prediksi'] = label_encoder.inverse_transform(y_pred2)

import numpy as np
from scipy.special import softmax

probs = softmax(logits, axis=1)
df3['confidence'] = np.max(probs, axis=1)

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
label_encoder.fit(y_train)

mapping = {
    0: "Anggaran",
    1: "Kualitas Pangan",
    2: "Distribusi",
    3: "Ekonomi",
    4: "Tata Kelola",
    5: "Sasaran Penerima",
    6: "Politik",
    7: "Lainnya"
}

df3['label_prediksi_nama'] = df3['label_prediksi'].map(mapping)

df3[['text_clean', 'label_prediksi', 'confidence']].head()

# Simpan dataframe ke file Excel
df3.to_excel('/content/drive/MyDrive/TIM Anomali SCP-03/Case 1/hasil_prediksi.xlsx', index=False)